title: Welcome to my page!
author: Dilcia Mercedes
description: |
  Hi ğŸ‘‹ğŸ¾ Iâ€™m Dilcia**. Iâ€™m a data journalist/developer and below are some of my recent projects. I have more projects in the works and am hoping to update this page soon. In the meantime, if you want to know more about me, you guessed it - check the <a href="about">about page</a> out. If you want to check my <a href="blog">blog posts</a> out, click here. 

permalink: /:slug

favicon: "./logo.png" # relative path to site's favicon
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  appearance_toggle: true 
  back_home_text: "home.." 
  date_format: "%Y-%m-%d" 
  show_description: true 
  show_navbar: true 
  show_footer: true 
  show_copyright: true 
  show_projects: true
  show_old_projects: true
  home:
    title_projects: Portfolio
    title_blog: Blog

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
